version: '3.8'

services:
  webapi:
    build: ./src/WebApi
    container_name: dotnet_webapi
    ports:
      - "8080:80"
    restart: always

  gremlin:
    image: gremlin/gremlin
    container_name: gremlin
    env_file:
      - ./gremlin/gremlin.env
    privileged: true
    network_mode: "host"
    restart: always
    depends_on:
      - webapi